mysql:
  host: localhost
  port: 3306
  database: github
  user: gituser
  password: gitpassword
  params:
  - "charset=utf8mb4"
  - "parseTime=true"
jwt:
  secret: "HAiOjE1NDI1OTU2ODgsInVpZCI6MSwidXNlcm5hbWUiOiJjb29rZWVt"
users:
  host: localhost
  port: 8080
gitrepos:
  host: localhost
  port: 8081
reviews:
  host: localhost
  port: 8082
