mysql:
  host: localhost
  port: 3306
  database: github
  user: gituser
  password: gitpassword
  params:
  - "charset=utf8mb4"
  - "parseTime=true"
jwt:
  secret: "iZXhwIjoxNTQyODY2ODA0LCJpYXQiOjE1NDI4NjU5MDQsImlzcyI6Imdp"
backend:
  port: 3000
users:
  host: localhost
  port: 8080
gitrepos:
  host: localhost
  port: 8081
reviews:
  host: localhost
  port: 8082
