mysql:
  host: localhost
  port: 3306
  database: github
  user: gituser
  password: gitpassword
  params:
  - "charset=utf8mb4"
  - "parseTime=true"
jwt:
  secret: "iZXhwIjoxNTQyODY2ODA0LCJpYXQiOjE1NDI4NjU5MDQsImlzcyI6Imdp"
  expires: 900
backend:
  port: 3000
users:
  host: localhost
  port: 3001
gitrepos:
  host: localhost
  port: 3002
reviews:
  host: localhost
  port: 3003
