mysql:
  # 测试环境使用localhost
  host: gitrepo-mysql
  port: 3306
  database: github
  user: gituser
  password: gitpassword
  params:
  - "charset=utf8mb4"
  - "parseTime=true"
jwt:
  secret: "iZXhwIjoxNTQyODY2ODA0LCJpYXQiOjE1NDI4NjU5MDQsImlzcyI6Imdp"
  expires: 900
backend:
  port: 3000
  corsAllow: true
users:
  # 测试环境使用localhost
  host: gitrepo-user
  port: 3001
gitrepos:
  # 测试环境使用localhost
  host: gitrepo-gitrepo
  port: 3002
reviews:
  # 测试环境使用localhost
  host: gitrepo-review
  port: 3003
