version: '3'
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.13
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: headline
      MYSQL_USER: hluser
      MYSQL_PASSWORD: hlpasswd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - "3306:3306"
