version: '3'
services:
  gitrepo-mysql:
    container_name: gitrepo-mysql
    hostname: gitrepo-mysql
    # 需要先把镜像推送到harbor
    image: mysql:5.7.24
    # 指定容器装载本地文件系统
    volumes:
    - ./gitrepo-mysql:/var/lib/mysql
    # 通过环境变量指定mysql的启动参数
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: github
      MYSQL_USER: gituser
      MYSQL_PASSWORD: gitpassword
    ports:
    - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
